# -*- coding: utf-8 -*-
"""E_Commerce sales analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLXxub8UrFhY61uFhG9rlp-TUCjAezvw
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
file_path = '/content/analysis.csv'  # Adjust if necessary
data = pd.read_csv(file_path)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('InvoiceDate').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_17['Quantity'].plot(kind='line', figsize=(8, 4), title='Quantity')
plt.gca().spines[['top', 'right']].set_visible(False)

from google.colab import drive
drive.mount('/content/drive')

# Check for missing values
print("Missing values per column:")
print(data.isnull().sum())

# Drop rows with missing values (or fill them if needed)
data.dropna(inplace=True)

# Convert 'Order_Date' column to datetime if present
if 'Order_Date' in data.columns:
    data['Order_Date'] = pd.to_datetime(data['Order_Date'])

# Check data types to ensure correct formats
data.info()

# Calculate total sales
if 'Amount' in data.columns:
    total_sales = data['Amount'].sum()
    print(f"Total Sales: ${total_sales:,.2f}")
else:
    print("Amount column not found.")

# Best-Selling Products
if 'Description' in data.columns and 'Amount' in data.columns:
    top_products = data.groupby('Description')['Amount'].sum().sort_values(ascending=False).head(10)
    print("Top 10 Best-Selling Products:")
    print(top_products)
else:
    print("Description or Amount column not found.")

# Customer Purchase Frequency
if 'CustomerID' in data.columns:
    customer_purchase_counts = data['CustomerID'].value_counts()
    print("Top 10 Customers by Purchase Frequency:")
    print(customer_purchase_counts.head(10))
else:
    print("CustomerID column not found.")

# Top 10 Products Bar Plot
if 'Description' in data.columns and 'Amount' in data.columns:
    plt.figure(figsize=(12, 6))
    top_products.plot(kind='bar', color='orange')
    plt.title('Top 10 Best-Selling Products')
    plt.xlabel('Product')
    plt.ylabel('Total Sales ($)')
    plt.xticks(rotation=45)
    plt.show()
else:
    print("Description or Amount column not found.")

# Customer Purchase Frequency Histogram
if 'CustomerID' in data.columns:
    plt.figure(figsize=(10, 6))
    sns.histplot(customer_purchase_counts, bins=30, kde=True, color='green')
    plt.title('Customer Purchase Frequency Distribution')
    plt.xlabel('Number of Purchases')
    plt.ylabel('Number of Customers')
    plt.show()
else:
    print("CustomerID column not found.")

